name: List Files

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the test on'
        required: true
        default: 'tf-modules'  # Set the default value to tf-modules

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -la
