name: List Files

on:
  workflow_dispatch:
    branches:
      - tf-modules

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -la
